### PR TITLE
Add suport for baseline audio HAL and PFW-based audio HAL in same tree

### PR DESCRIPTION
**Pull request by plbossart**
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by kalyankondapally** [comment]
MIssing:

Jira: (Link to Jira)

Test: (What tests are expected to pass).

Commit template uniform across project: https://github.com/android-ia/manifest/wiki/Contributions

**Comment by plbossart** [comment]
the commit does not change any functionality at this point, it just prepares for the support for the PFW-based HAL which remains compiled out. I don't know what JIRA or test you'd want, it's somewhat meaningless here.

**Comment by kalyankondapally** [comment]
@plbossart This is for consistency with commit template. In this case it could be: Jira: None, Tests: repo sync should succeed.  Opening a Jira is not mandatory unless this is a bug fix.

**Comment by kalyankondapally** [comment]
merged

**Pull request closed without merging**
